# Generated by Django 4.2.2 on 2023-09-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(default="Martin J Walls", max_length=255)),
                ("description", models.TextField()),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
